steps:
  - name: Install bower
    plugin: Shell
    command: 'npm install -g bower'
  - name: Install NPM packages
    command: 'npm install'
  - name: Install bower dependencies
    command: 'bower install'
  - name: Execute maven build
    command: 'mvn install -DskipTests'