language: node_js
node_js:
  - "4.4"
sudo: false
before_install:
  - npm install -g gulp
  - npm install -g bower
install:
  - npm install
  - bower install
before_script: gulp build
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false