version: '2'
services:
    cpv-app:
        image: cpv
        external_links:
            - cpv-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cpv?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    cpv-mysql:
        extends:
            file: mysql.yml
            service: cpv-mysql
