on: [push]

jobs:
    codescan:
        runs-on: ubuntu-latest
        steps:
            -   name: Run Analysis
                uses: borisbsu/codescan-scanner-action@master
                with:
                    login: ${{ secrets.SONAR_TOKEN }}
                    organization: 5efa11fdda6b0c001320f461
                    projectKey: continious-delivery-test
                    codeScanUrl: https://test.codescan.io/
                    args: >
                        -Dsonar.test.exclusions=tests/**
                        -Dsonar.tests=tests/
                        -Dsonar.verbose=true
            -   name: Browse folder
                run: ls -la
            -   name: Cat report-task.txt
                run: .scannerwork/report-task.txt
