on: [push]

jobs:
    codescan:
        runs-on: ubuntu-latest
        steps:
            -   name: Run Analysis
                uses: borisbsu/codescan-scanner-action@main
                with:
                    login: ${{ secrets.SONAR_TOKEN }}
                    organization: 5efa11fdda6b0c001320f461
                    projectKey: continious-delivery-test
                    codeScanUrl: https://test.codescan.io/
                    args: >
                        sonar.test.exclusions=tests/**
                        sonar.tests=tests/
                        sonar.verbose=true
            -   name: Browse folder
                run: ls -la
            -   name: Browse folder
                run: ls -la .scannerwork
            -   name: Cat report-task.txt
                run: .scannerwork/report-task.txt
